export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS"
export const GET_NEWS_LOADING = "GET_NEWS_LOADING"
export const GET_NEWS_ERROR="GET_NEWS_ERROR"

export const GET_NEWS_HEADLINES_SUCCESS ="GET_NEWS_HEADLINES_SUCCESS"
export const GET_NEWS_HEADLINES_ERROR="GET_NEWS_HEADLINES_ERROR"
export const GET_NEWS_HEADLINES_LOADING="GET_NEWS_HEADLINES_LOADING"

export const GET_POPULAR_NEWS_ERROR="GET_POPULAR_NEWS_ERROR"
export const  GET_POPULAR_NEWS_SUCCESS="GET_POPULAR_NEWS_SUCCESS"
export const  GET_POPULAR_NEWS_LOADING="GET_POPULAR_NEWS_LOADING"

export const GET_CRUNCH_NEWS_SUCCESS="GET_CRUNCH_NEWS_SUCCESS"
export const GET_CRUNCH_NEWS_ERROR="GET_CRUNCH_NEWS_ERROR"
export const GET_CRUNCH_NEWS_LOADING="GET_CRUNCH_NEWS_LOADING"

export const GET_WALL_STREET_SUCCESS="GET_WALL_STREET_SUCCESS"
export const GET_WALL_STREET_ERROR="GET_WALL_STREET_ERROR"
export const GET_WALL_STREET_LOADING="GET_WALL_STREET_LOADING"